version: "3"
services:
  app:
    build: C:\Users\GSC-30702\PycharmProjects\Employee_Info
    links:
      - db
    ports:
      - "5000:5001"

  db:
    image: mysql:8.0.21
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro